version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "3050:3050"
    env_file:
      - ./backend/.env
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
