# Finds and fixes problems in JavaScript code
name: lint

# workflow triggers
on:
  workflow_dispatch:
  workflow_call:

jobs:
  eslint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install --prefix backend
      - name: Run ESLint
        run: cd backend && npx eslint
  eslint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install --prefix frontend
      - name: Run ESLint
        run: cd frontend && npx eslint