# Finds and fixes problems in JavaScript code
name: lint

# workflow triggers
on:
  workflow_dispatch:
  workflow_call:

jobs:
  eslint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: cd backend
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx
  eslint-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd frontend
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: eslint . --ext .js,.jsx,.ts,.tsx