# makes code look prettier in a constant way
name: prettier

# workflow triggers
on:
  workflow_dispatch:
  workflow_call:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
      - run: ls
      - run: pwd
      - name: Prettify code in frontend
        uses: creyD/prettier_action@v4.3
        with:
          commit_message: "Prettified frontent Code!"
          working_directory: "frontend/"
      - name: Prettify code in backend
        uses: creyD/prettier_action@v4.3
        with:
          commit_message: "Prettified backend Code!"
          working_directory: backend
