name: Pull Request Checks

# workflow triggers
on:
  workflow_dispatch:
  workflow_call:
  pull_request:

jobs:
  prettier:
    uses: ./.github/workflows/prettier.yml
  lint:
    uses: ./.github/workflows/lint.yml
