name: Pull Request Checks

# workflow triggers
on:
  workflow_dispatch:
  workflow_call:
  pull_request:

jobs:
  checkCode:
    uses: ./.github/workflows/checkCode.yml
  prettier:
    needs: checkCode
    uses: ./.github/workflows/prettier.yml
