# checks css code
name: stylelint

# workflow triggers
on:
  workflow_dispatch:
  workflow_call:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: stylelint 
        uses: actions-hub/stylelint@master
