name: 'test'
on:
    workflow_dispatch:
    workflow_call:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Backend
              run: npm install --prefix backend
            - name: Test Backend
              run: npm test --prefix backend
            - name: Install Frontend
              run: npm install --prefix frontend
            - name: Test Frontend
              run: npm test --prefix frontend
            - uses: ArtiomTr/jest-coverage-report-action@v2